<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8I0up7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8I0up7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8I0up7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8I0up7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV8I0up7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V8I0up7',
    'container.build_id' => '1e2e71eb',
    'container.build_time' => 1606943331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8I0up7');
