-- MySQL Script generated by MySQL Workbench
-- mar. 01 déc. 2020 19:42:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `idFlights` INT NOT NULL,
  `Flights_departure` VARCHAR(3) NOT NULL,
  `Flights_arrival` VARCHAR(3) NOT NULL,
  `Flights_date` TIMESTAMP(6) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`idFlights`),
  UNIQUE INDEX `idFlights_UNIQUE` (`idFlights` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `idTransactions` INT NOT NULL,
  `idFlights` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idTransactions`),
  INDEX `idFligths_idx` (`idFlights` ASC),
  CONSTRAINT `idFligths`
    FOREIGN KEY (`idFlights`)
    REFERENCES `mydb`.`Flights` (`idFlights`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
